### ISSUE TITLE
display_region problems

### ISSUE THREAD

**Issue by hoba87** [Cheaterman/panda3d-kivy#10]
If using the basic example from readme with the display_region option 
`display_region=self.win.make_display_region(0, 1, 0, 1)`
then everything is fine. However if changing the values e.g. to (0, 1, 0, 0.5), the button cannot be clicked, while with (0, 0.5, 0, 1) it is still working.

**Comment by Cheaterman** [comment]
Minimal example:
```python
from panda3d_kivy.app import App
from kivy.uix.button import Button
from direct.showbase.ShowBase import ShowBase


class Example(App):
    def build(self):
        return Button(text='Hello, world!')


class PandaApp(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)

        display_region = self.win.make_display_region(0, 1, 0, 0.5)

        # If you uncomment this, it works
        #display_region = self.win.make_display_region(0, 1, 0, 1)

        self.kivy_app = kivy_app = Example(self, display_region)
        kivy_app.run()


app = PandaApp()
app.run()
```
I was pretty surprised that I reproduced this to be honest, I'll need to investigate further. Thanks a lot for your report!

**Comment by PentalimbedPuss** [comment]
I believe there is a general problem of translating coordinates in display region that doesn't occupy the entire window. For example if you take the pong game from kivy's official tutorial ([https://kivy.org/doc/stable/tutorials/pong.html](url)) and put it inside a display region of a size like (0, 0.6, 0, 0.6) or (0.25, 0.75, 0.25, 0.75), you can see how heavily the paddles' position shifts away from where you clicked, that you have to click much higher.

**Comment by cubeslinger** [comment]
Any news or workaround to this issue? sadly it's a showstopper to me.

**Comment by Cheaterman** [comment]
I'm so sorry, I've been very busy with work since then. PRs are welcome FWIW, or if you're patient I might take a look at it soon-ish.

**Comment by Cheaterman** [comment]
Good news everyone :-) it's finally fixed. You're more than welcome to test it in your own apps, make sure I didn't break anything for you... this deserves more tests, but these tests will be a bit complicated to write (plenty of mocking going on, and getting the right behavior from the mocks will be complicated given how many moving pieces are involved in both frameworks...).

**Comment by Melan2001** [comment]
Hi Cheaterman: I can confirm that I do not have noticed any regression with this upate. Thanks for the update!

**Comment by Cheaterman** [comment]
> Hi Cheaterman: I can confirm that I do not have noticed any regression with this upate. Thanks for the update!

Thanks a lot for your feedback @Melan2001 ! I'm glad it works well for you - and sorry for taking nearly a year to land this bugfix hahaha :smile: thanks again for your patience everyone! Happy Panda-Kivy-ing :smile:
