### ISSUE TITLE
I just want to say, you are AWESOME!

### ISSUE THREAD

**Issue by gr4viton** [Cheaterman/panda3d-kivy#20]
There I was learning panda3d, and thinking about using kivy for the GUI, because I knew kivy from before and thought it would be awesome combo :fire: . And then I found your package. Mister Cheaterman, you are AWESOME. Thank you!

This is not really an issue, sorry. I just needed to say it. Thank you! :fire:

**Comment by Cheaterman** [comment]
Hahahaha, I'm very happy that you like it! Sometimes it's the simplest projects that have the most impact :-)
