### ISSUE TITLE
Latest kivy version (2.1.0) prevents 3D objects to be displayed

### ISSUE THREAD

**Issue by Melan2001** [Cheaterman/panda3d-kivy#22]
Installing panda3d-kivy 0.3.0 makes the installation of the latest kivy version (2.1.0).

With the 2.1.0 version : 
- kivy uix objects are displayed
- 2D objects such as TextNode are displayed
- but no 3D objects are displayed (only a black screen)

With the downgrade to kivy 2.0.0, the 3D objects are displayed again.

Tested also with the 'movement' sample provided in the source code.

Specs:
panda3d 1.10.11 - x64
panda3d-kivy 0.3.0 (pip installed)
Python 3.7.9
OS: Windows 11
3080 TI mobile

**Comment by fdr2** [comment]
I'm having what seems to be a similar issue. M1 (arm64) Monterey (Panda3D==1.10.11.post1, panda3d-kivy==0.3.0, Python==3.9.12)

The kivy app works, and I have no reason to believe without testing, the integration is successful. Although, I see a black screen with my kivy ui widgets. My panda app is not visible, but kivy buttons register. It's almost like i need my kivy app to be transparent so I can see panda or only fill a portion of window when I need to hud, but I haven't figured out how...

**Comment by Melan2001** [comment]
A quick workaround is to comment these lines in __init__.py (l. 1527) in the kivy\core\window directory (however not 100% sure it has no side effect...):
```
def clear(self):
       '''Clear the window with the background color'''
        # XXX FIXME use late binding
        from kivy.graphics import opengl as gl
        #gl.glClearColor(*self.clearcolor)
        #gl.glClear(
        #    gl.GL_COLOR_BUFFER_BIT
        #    | gl.GL_DEPTH_BUFFER_BIT
        #    | gl.GL_STENCIL_BUFFER_BIT
        #)
```
@Cheaterman will certainly have a more robust solution.

**Comment by fdr2** [comment]
in lines 483-484 of the file @Melan2001 mentioned, I found this which worked for me.
```python
        # don't clear background at all
        Window.clearcolor = None
```

the equivalent in panda3d-kivy (my case) is be
```python
class HudApp(App):
    def build(self):
        self.window.clearcolor = None
        return HudGui()
```

**Comment by fdr2** [comment]
ehh, scratch that. when I use the code in the last comment AND the HudApp class, I get the error `None is not allowed for PandaWindow.clearcolor`. I replaced HudApp with a DirectFrame subclass when I thought the above worked.

**Comment by thomassedlmayer** [comment]
Same problem occurs to me with python 3.7.9, kivy 2.1.0 and panda3d 1.10.11. As soon as a kivy gui element is rendered on top of any panda3d stuff, the screen turns black. Did anyone find a fix for this or have any idea what causes the issue? With kivy 2.0.0 the issue does not appear to happen.

**Comment by Melan2001** [comment]
> Same problem occurs to me with python 3.7.9, kivy 2.1.0 and panda3d 1.10.11. As soon as a kivy gui element is rendered on top of any panda3d stuff, the screen turns black. Did anyone find a fix for this or have any idea what causes the issue? With kivy 2.0.0 the issue does not appear to happen.

Have you tried the workaround proposed above? 
`https://github.com/Cheaterman/panda3d-kivy/issues/22#issuecomment-1160840869`

After several months of usage, I do not see any side effect using this workaround...

**Comment by Cheaterman** [comment]
I think your workaround is great - the only issue I have is that I would prefer to know exactly why this happened before fixing it, because there's still a possibility that this was unintentional breakage introduced by Kivy that could need to be fixed/reverted in Kivy itself :-) I'll make time to look into this today, I'll keep everyone in touch here!

**Comment by Melan2001** [comment]
> I think your workaround is great - the only issue I have is that I would prefer to know exactly why this happened before fixing 
it

Of course, that makes sense. 

> EDIT: @Melan2001 do you know if your workaround breaks on Kivy <2.1.0 BTW?

No, unfortunately, I haven't tested that. 


> I'll make time to look into this today, I'll keep everyone in touch here!

Thanks!

**Comment by Cheaterman** [comment]
OK, I found the issue in Kivy and reported it: https://github.com/kivy/kivy/issues/8011

I pushed a fix to panda3d-kivy and I made a release:
- On GitHub: https://github.com/Cheaterman/panda3d-kivy/releases/tag/v0.4.0
- On PyPI: https://pypi.org/project/panda3d-kivy/0.4.0/

Thanks to everyone for your help and patience!

**Comment by Melan2001** [comment]
Thanks to you. Works well!
