### ISSUE TITLE
Dropdown and popup widgets use Kivy Window and not PandaWindow

### ISSUE THREAD

**Issue by Melan2001** [Cheaterman/panda3d-kivy#4]
Using the dropdown widget, there is an issue at line 216 (in kivy.uix.dropdown) :
```
     Window.bind(
        on_key_down=self.on_key_down,
        size=self._reposition)
```
With Window imported (l.99):
`from kivy.core.window import Window`

Bind is not possible because Window is None. I assume that in panda3d_kivy, Window should be replaced by PandaWindow. A "workaround" is possible by commenting these lines but this *should* (as far as I can understand) prevent use of  keys for this widget.

There is (as far as I can understand) the same issue for the popup widget (line 254 in kivy.uix.popup):
`Window.add_widget(layout)`
and Window imported as (line 236):
`from kivy.core.window import Window`
For the popup issue, the logfile indicates:
Output in log file:
[WARNING] [ModalView   ] cannot open view, no window found.

**Comment by Cheaterman** [comment]
Good one! I'm not surprised this happens, I'll have to look! Thanks for reporting :-)

**Comment by Melan2001** [comment]
Thanks !

Tested with the 0.1.2 fix: 
The pop up is working now but not the drop down issue (and spinner) is still here.

**Comment by Melan2001** [comment]
With the main and kv files. Not very clean but should be ok. Thanks !


[Main_spinner_works.zip](https://github.com/Cheaterman/panda3d-kivy/files/4396973/Main_spinner_works.zip)

**Comment by Melan2001** [comment]
I found that putting:
       ` from kivy.core.window import Window`
before line 216 corrects the situation.
