### ISSUE TITLE
P3D displays a GL error message when P3D config. var. gl-version is set above 3 0

### ISSUE THREAD

**Issue by Melan2001** [Cheaterman/panda3d-kivy#5]
Using the configuration variable in Panda3d (used to setup a particular GL context):
`gl-version 4 3`

makes P3D/kivy throwing an error in the console (even if the program works):
(details obtained by setting the `gl-debug #t` in the config variables of P3D):

[INFO   ] [Logger      ] Record log in \.kivy\logs\kivy_20-03-15_20.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.2.0
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "\Panda3D-1.10.5-x64\python\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "\Panda3D-1.10.5-x64\python\ppython.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
:display:windisplay(warning): SetForegroundWindow() failed!
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
**:display:gsg:glgsg(error): Using glGetString in a Core context with parameter <name> and enum '0x1f03' which was removed from Core OpenGL (GL_INVALID_ENUM)**
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.3.13399 Core Profile/Debug Context 15.201.1151.1008'>
[INFO   ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'AMD Mobility Radeon HD 5800 Series'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 3
[INFO   ] [GL          ] Shading version <b'4.40'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <18>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
**:display:gsg:glgsg(error): Using glGetString in a Core context with parameter <name> and enum '0x1f03' which was removed from Core OpenGL (GL_INVALID_ENUM)**
[INFO   ] [GL          ] NPOT texture support is available
:display:gsg:glgsg(error): glUniformMatrix4fv has failed because the operation requires a currently active program object (GL_INVALID_OPERATION)
:display:gsg:glgsg(error): glUniformMatrix4fv has failed because the operation requires a currently active program object (GL_INVALID_OPERATION)
:display:gsg:glgsg(error): glUniformMatrix4fv has failed because the operation requires a currently active program object (GL_INVALID_OPERATION)
:display:gsg:glgsg(error): glUniformMatrix4fv has failed because the operation requires a currently active program object (GL_INVALID_OPERATION)
:display:gsg:glgsg(error): glUniformMatrix4fv has failed because the operation requires a currently active program object (GL_INVALID_OPERATION)
:display:gsg:glgsg(error): glUniformMatrix4fv has failed because the operation requires a currently active program object (GL_INVALID_OPERATION)
….again and again….

Setting the config variable until  `gl-version 3 0` makes P3D/kivy not issuing any error in the console.

**Comment by rdb** [comment]
I think the problem is that Kivy requires a compatibility context, and Kivy and Panda3D are sharing the same OpenGL context.

Fixing this would require either running Kivy and Panda3D in a separate GL context, or fixing Kivy to support core contexts (which would probably be a lot of work).

**Comment by Melan2001** [comment]
Thanks rdb!
Would the first alternative (separate GL context) you suggested be easy to implement?

**Comment by Cheaterman** [comment]
@Melan2001 Neither alternative is really easy to implement TBH, it might just be easier to fix your shaders (assuming that's the reason you need a specific GL version)?

**Comment by rdb** [comment]
> Would the first alternative (separate GL context) you suggested be easy to implement?

Upon further reflection, I don't actually think there's any good guarantee that context sharing will work for two contexts with different GL profiles, so this may be a non-starter.

**Comment by Melan2001** [comment]
Understood and thanks for your feeback.

@Cheaterman: reason for that is that I noticed on my (outdated) graphics card some performance improvement on my shaders setting the 4.3 context.

Suggestion: it _seems_  (not tested in an extensive manner) that setting the context above 3.0 is not preventing Kivy to work. So would it be possible to trap this GL error as it could be made silent?[it may be not a good idea...]

**Comment by rdb** [comment]
No, this is a terrible idea.  Kivy would be making invalid OpenGL calls.  If anything even works at all, it will not work well, and it's up to the mercy of the driver how it treats these invalid calls.

**Comment by Melan2001** [comment]
Thanks rdb.  So I'll probably need to live with that.  Unless cheaterman has an ultimate alternative, I'll close this issue.

**Comment by Cheaterman** [comment]
Nah, there's not much more to say about it. I totally believe rdb that this is a terrible idea ; if you have performance issues with some shaders somehow, you might want to fix these instead. Kivy has pretty strict requirements in terms of which kind of context it can run, because it needs to ensure GLES compatibility, so this might be why you won't be able to set the GL version equal to or above 3.0 in Panda.

**Comment by rdb** [comment]
It might be possible to use Kivy with OpenGL ES 2, and use it with the OpenGL ES 2 renderer of Panda3D?  I'm not sure if that will help your performance, but it's a hypothetical possibility.  It does lock you out of a lot of desktop OpenGL features in Panda3D, though.

**Comment by Melan2001** [comment]
OK, thanks for your suggestion rdb. 
If I decide to use Kivy for my main project,  I think I will probably use  gl-version 3 1 for the editor side (works until that version number for both Kivy and my main project) and the "executable" produced by the editor will probably  use a higher version.
