### ISSUE TITLE
P3D outputs a GL error when the checkbox color is not defined with 4 components 

### ISSUE THREAD

**Issue by Melan2001** [Cheaterman/panda3d-kivy#6]
When using this .kv file, P3D outputs a GL error.

```
#.kv file of main.py file 

#: import CheckBox kivy.uix.checkbox 

# giving colour to lable 
<CustLabel@Label>: 
	color: .761, .190, .810, 1

<SampBoxLayout>: 
	orientation: "vertical"
	padding: 10
	spacing: 10

	CustLabel: 
		text: "Gender"
		size_hint_x: 1
		font_size:20

	# creating box layout 
	BoxLayout: 
		# assigning orentation 
		orientation: "horizontal"
		height: 20

		BoxLayout: 
			orientation: "horizontal"
			size_hint_x: .22

			# label creation 
			CustLabel: 
				text: "Male"
				size_hint_x: .80
				font_size:30
			CheckBox: 
				**color:.294, .761, .623**
				on_active: root.checkbox_click(self, self.active) 
				size_hint_x: .20
```

GL error:
:display:gsg:glgsg(error): glUniform3f has failed to set the uniform at location '0': the uniform's type, component size, or matrix dimensions are incompatible with the function variant (GL_INVALID_OPERATION)

Issue is that the checkbox color (see ** **) is defined with 3 components. Setting the alpha component solves this issue. 

Not sure if something could be done to 1/ raise a proper warning or 2/ put a default alpha component to 1.0

**Comment by Cheaterman** [comment]
The thing is, that's just how Kivy works: https://kivy.org/doc/stable/api-kivy.uix.checkbox.html#kivy.uix.checkbox.CheckBox.color

You're supposed to provide all four components, that's it :-)

Closing as this is neither an issue with Panda3D nor with Kivy.

**Comment by Cheaterman** [comment]
(Just tested in Kivy, it fails silently - maybe you could reopen the issue there?)

**Comment by rdb** [comment]
For the record, while the GL error is being caught by Panda's debug layer, I think the GL call in question actually originates in Kivy.  Panda automatically converts shader input types.
