### ISSUE TITLE
Kivy is not starting when P3D threading model is activated

### ISSUE THREAD

**Issue by Melan2001** [Cheaterman/panda3d-kivy#7]
When using the P3D threading model in the config file:
`threading-model Cull/Draw` or even `threading-model /Draw`

Kivy is not starting and displays this message (from the log file):

[INFO   ] Logger: Record log in \.kivy\logs\kivy_20-03-22_3.txt
[INFO   ] deps: Successfully imported "kivy_deps.glew" 0.2.0
[INFO   ] deps: Successfully imported "kivy_deps.sdl2" 0.2.0
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "\Panda3D-1.10.6-x64\python\lib\site-packages\kivy\__init__.py"
[INFO   ] Python: v3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
[INFO   ] Python: Interpreter at "\Panda3D-1.10.6-x64\python\python.exe"
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
**[ERROR  ] GL: GLEW initialization error b'Missing GL version'**

**Comment by Cheaterman** [comment]
Oh wow, it's pretty impressive that it doesn't crash! I guess we need to have to make sure Kivy is rendering inside of Panda's draw thread for this to work, but I'm not sure how to achieve that - I would have imagined the display region callbacks are already called from the proper thread. Possibly has to do with Kivy being initialized too early (when importing or instancing the App)?

**Comment by Melan2001** [comment]
Well, I don't know how exactly the threading model is working under the hood but it is probably one of the thing in Panda that is regularly improved due to numerous bugs found. This is a typical question for rdb I guess...

**Comment by rdb** [comment]
The long and short of it is that with pipelining enabled, all calls to OpenGL *must* happen from within the draw thread.  This means all Kivy initialization calls that make OpenGL calls must also be done inside a draw callback.

**Comment by Cheaterman** [comment]
For reference, as rdb said "in case it's needed" :
```
12:59:36 < rdb> Creating the window in the draw callback is clearly the way to go, but you can force this to happen by forcibly rendering a frame in the initialization
12:59:45 < rdb> Then you can ensure that the window has indeed been created by the time you finish initing
13:00:00 < rdb> (You may need to render multiple frames, or use sync_frame, to have it go through the pipeline)
13:00:01 < Cheaterman> Interesting, but that feels more like a hack than what we implemented, right?
13:00:11 < rdb> Well, I'm just saying it just in case it may turn out to be necessary
```

**Comment by Melan2001** [comment]
Tested and it works perfectly. Thanks to you both!
